FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Увеличиваем таймаут для pip
RUN pip install --no-cache-dir --default-timeout=100 -r requirements.txt

# Установка coverage для отчётов по тестам
RUN pip install coverage --default-timeout=100

# Создание конфигурации coverage
RUN echo "[run]\nsource = .\nomit = */tests/*, */migrations/*, */admin.py" > .coveragerc

COPY . .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]